module.exports = {
    DOCUMENT_DB_ENDPOINT: process.env.DOCUMENT_DB_ENDPOINT || 'https://botcosmosdb.documents.azure.com:443/',
    DOCUMENT_DB_PRIMARYKEY: process.env.DOCUMENT_DB_PRIMARYKEY || 'U9yg4qhVkKtol6p1nyMpoWpdSISpKwZLIwXFoaUqF9UPsC4HZMng2ZKYfu5p81kPg05HwIm4B2BV7BEuZxrEaw==',
    DOCUMENT_DB_DATABASE: process.env.DOCUMENT_DB_DATABASE || 'BotDB',
    DOCUMENT_DB_FLIGHT_COLLECTION: process.env.DOCUMENT_DB_FLIGHT_COLLECTION || 'Flights',
    DOCUMENT_DB_BOOKING_COLLECTION: process.env.DOCUMENT_DB_BOOKING_COLLECTION || 'Bookings',
    DOCUMENT_DB_ALTERNATIVE_FLIGHT_COLLECTION: process.env.DOCUMENT_DB_ALTERNATIVE_FLIGHT_COLLECTION || 'AlternativeFlights'
};

